// Displacers and Base configuration
#define DISPLACER_X_DIRECTION_PIN 2
#define DISPLACER_Y_DIRECTION_PIN 2
#define DISPLACER_Z_DIRECTION_PIN 2

#define DISPLACER_X_STEP_PIN 3
#define DISPLACER_Y_STEP_PIN 4
#define DISPLACER_Z_STEP_PIN 5

// Injectors configuration
#define INJECTOR_1_PUMP_DIRECTION_PIN 7
#define INJECTOR_2_PUMP_DIRECTION_PIN 7
#define INJECTOR_3_PUMP_DIRECTION_PIN 7
#define INJECTOR_4_PUMP_DIRECTION_PIN 7

#define INJECTOR_1_PUMP_STEP_PIN 8
#define INJECTOR_2_PUMP_STEP_PIN 9
#define INJECTOR_3_PUMP_STEP_PIN 10
#define INJECTOR_4_PUMP_STEP_PIN 11

#define INJECTOR_1_LOCATION_X 50000           // Micrometres
#define INJECTOR_1_LOCATION_Y 0
#define INJECTOR_1_LOCATION_Z 0

#define INJECTOR_2_LOCATION_X 60000
#define INJECTOR_2_LOCATION_Y 0
#define INJECTOR_2_LOCATION_Z 0

#define INJECTOR_3_LOCATION_X 70000
#define INJECTOR_3_LOCATION_Y 0
#define INJECTOR_3_LOCATION_Z 0

#define INJECTOR_4_LOCATION_X 80000
#define INJECTOR_4_LOCATION_Y 0
#define INJECTOR_4_LOCATION_Z 0

// Other configuration
#define INJECTING_STARTING_POINT_Z 100000     // Micrometres
